fix: Added `not found` errors to classifier
cloudquery/cq-provider-k8s pull request #166
Opened 2022-06-09 12:23 UTC by amanenk

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

- adds `not found` errors to ErrorClassifier. k8s server returns 404 when not supported resource is fetched

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [ ] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] Ensure the status checks below are successful ✅

2022-06-09 12:32 UTC, erezrokah requested changes
Nice fix, one comment on the messaging

2022-06-09 12:32 UTC, erezrokah commented on client/errors.go
> +			return diag.FromError(ie, diag.RESOLVING, diag.WithSeverity(diag.IGNORE), diag.WithDetails("Current version of k8s might not support requested resource"))
```suggestion
			return diag.FromError(ie, diag.RESOLVING, diag.WithSeverity(diag.IGNORE), diag.WithDetails("Current version of k8s might not support the requested resource"))
```

Can we recommend an action item to the user? e.g. updating something with their `k8s` environment?

2022-06-10 08:31 UTC, yevgenypats approved these changes

2022-06-13 06:47 UTC, erezrokah commented on client/errors.go
> +			return diag.FromError(ie, diag.RESOLVING, diag.WithSeverity(diag.IGNORE), diag.WithDetails("Current version of k8s might not support requested resource"))
To follow up on my intention with my comment, does the following message makes sense:
```
"Current version of k8s might not support the requested resource. Consider upgrading your k8s to the most recent version"
```

Also, is this something we can detect in advance? If a k8s version doesn't support a resource, we shouldn't try to fetch it. Is this a valid action item to handle in a separate future PR?

2022-06-13 12:08 UTC, erezrokah approved these changes

2022-06-13 12:13 UTC, erezrokah approved these changes

2022-06-13 12:19 UTC, merged